Repository cdktf/projen-cdktf-hybrid-construct, pull requests merged in 2024-08, with the labels that each got.

#163 chore(deps): upgrade dependencies
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  package.json
  yarn.lock
Labels: auto-approve, dependencies, automerge

#164 chore(deps): upgrade dependencies
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  package.json
  yarn.lock
Labels: auto-approve, dependencies, automerge

#165 chore(deps): upgrade dependencies
  examples/hybrid-module/yarn.lock
  examples/terraform-module/yarn.lock
  yarn.lock
Labels: auto-approve, dependencies, automerge

#166 chore(deps): upgrade dependencies
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  yarn.lock
Labels: auto-approve, dependencies, automerge

#167 chore(ci): fix syntax for concurrency in workflows
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/upgrade-cdktf.yml
  projenrc/auto-approve.ts
  projenrc/automerge.ts
  projenrc/upgrade-cdktf.ts
Labels: automerge

#168 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
Labels: dependencies, automerge

#169 chore(deps)!: increase minimum required version of Projen to 0.85
  .eslintrc.json
  .github/workflows/build.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  API.md
  README.md
  examples/hybrid-module/.eslintrc.json
  examples/hybrid-module/.github/workflows/build.yml
  examples/hybrid-module/.github/workflows/pull-request-lint.yml
  examples/hybrid-module/.github/workflows/release.yml
  examples/hybrid-module/.github/workflows/upgrade-main.yml
  examples/hybrid-module/.npmignore
  examples/hybrid-module/.projen/deps.json
  examples/hybrid-module/.projen/tasks.json
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/.eslintrc.json
  examples/terraform-module/.github/workflows/build.yml
  examples/terraform-module/.github/workflows/pull-request-lint.yml
  examples/terraform-module/.github/workflows/release.yml
  examples/terraform-module/.github/workflows/upgrade-main.yml
  examples/terraform-module/.npmignore
  examples/terraform-module/.projen/deps.json
  examples/terraform-module/.projen/tasks.json
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  package.json
  test/__snapshots__/hybrid-module.test.ts.snap
  test/__snapshots__/terraform-module.test.ts.snap
  yarn.lock
Labels: dependencies

#170 chore(deps): upgrade jsii & typescript to v5.4 in examples
  examples/hybrid-module/.projen/deps.json
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/.projen/deps.json
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  src/hybrid-module.ts
  src/terraform-module.ts
  test/__snapshots__/hybrid-module.test.ts.snap
  test/__snapshots__/terraform-module.test.ts.snap
Labels: dependencies
