Repository cdktf/projen-cdktf-hybrid-construct, pull requests merged in 2025-01, with the labels that each got.

#176 chore(deps): upgrade dependencies
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/package.json
  examples/terraform-module/src/.gen/constraints.json
  examples/terraform-module/yarn.lock
  package.json
  yarn.lock
Labels: auto-approve, dependencies, automerge

#183 chore(ci): add workflow for upgrading jsii & typescript
  .gitattributes
  .github/workflows/upgrade-jsii-typescript.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/upgrade-jsii-typescript.ts
  scripts/update-jsii-typescript.sh
  yarn.lock
Labels: auto-approve, automerge

#182 chore(ci): add setup-terraform step in release workflow
  .github/dependabot.yml
  .github/workflows/release.yml
  .projenrc.ts
  examples/hybrid-module/.github/workflows/release.yml
  examples/terraform-module/.github/workflows/release.yml
  src/hybrid-module.ts
  src/terraform-module.ts
  test/__snapshots__/hybrid-module.test.ts.snap
  test/__snapshots__/terraform-module.test.ts.snap
Labels: auto-approve, automerge

#184 chore(deps)!: increase minimum required version of Projen to 0.88
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-projen.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  API.md
  README.md
  examples/hybrid-module/.gitattributes
  examples/hybrid-module/.github/workflows/build.yml
  examples/hybrid-module/.github/workflows/release.yml
  examples/hybrid-module/.github/workflows/upgrade-main.yml
  examples/hybrid-module/.projen/deps.json
  examples/hybrid-module/.projen/tasks.json
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/.gitattributes
  examples/terraform-module/.github/workflows/build.yml
  examples/terraform-module/.github/workflows/release.yml
  examples/terraform-module/.github/workflows/upgrade-main.yml
  examples/terraform-module/.projen/deps.json
  examples/terraform-module/.projen/tasks.json
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  package.json
  projenrc/upgrade-projen.ts
  scripts/update-projen.sh
  test/__snapshots__/hybrid-module.test.ts.snap
  test/__snapshots__/terraform-module.test.ts.snap
  yarn.lock
Labels: auto-approve, automerge

#181 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-projen.yml
  .projenrc.ts
Labels: auto-approve, automerge

#185 chore(ci): add setup-terraform step to upgrade workflows
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-projen.yml
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-jsii-typescript.ts
  projenrc/upgrade-projen.ts
Labels: auto-approve, automerge

#186 chore: upgrade jsii & typescript to v5.5
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  examples/hybrid-module/.projen/deps.json
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/.projen/deps.json
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  package.json
  src/hybrid-module.ts
  src/terraform-module.ts
  test/__snapshots__/hybrid-module.test.ts.snap
  test/__snapshots__/terraform-module.test.ts.snap
  yarn.lock
Labels: auto-approve, automerge, automated

#187 docs: create maintenance guide
  .github/MAINTENANCE.md
Labels: auto-approve, automerge

#189 chore(ci): fix misconfiguration in Projen upgrade workflow
  .github/MAINTENANCE.md
  .github/workflows/upgrade-projen.yml
  projenrc/upgrade-projen.ts
Labels: auto-approve, automerge

#188 chore(ci): update required version of constructs when cdktf is upgraded
  .github/MAINTENANCE.md
  .github/workflows/upgrade-cdktf.yml
  .projen/deps.json
  .projenrc.ts
  API.md
  README.md
  examples/hybrid-module/.projen/deps.json
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/.projen/deps.json
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  package.json
  projenrc/upgrade-cdktf.ts
  scripts/update-cdktf.sh
  src/hybrid-module.ts
  src/terraform-module.ts
  test/__snapshots__/hybrid-module.test.ts.snap
  test/__snapshots__/terraform-module.test.ts.snap
  yarn.lock
Labels: auto-approve, automerge

#191 chore(deps): upgrade dependencies
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  yarn.lock
Labels: auto-approve, dependencies, automerge

#192 chore(deps): upgrade dependencies
  examples/hybrid-module/yarn.lock
  examples/terraform-module/yarn.lock
  yarn.lock
Labels: auto-approve, dependencies, automerge

#190 chore(ci): fix linter misconfiguration to allow Projen upgrade to succeed
  .projen/tasks.json
  .projenrc.ts
  examples/hybrid-module/.projen/tasks.json
  examples/hybrid-module/src/__tests__/index-test.ts
  examples/hybrid-module/src/index.ts
  examples/hybrid-module/src/tfModules.ts
  examples/terraform-module/.projen/tasks.json
  examples/terraform-module/src/__tests__/index-test.ts
  examples/terraform-module/src/index.ts
  src/hybrid-module.ts
  src/terraform-module.ts
Labels: auto-approve

#193 chore(deps): upgrade dependencies
  examples/hybrid-module/yarn.lock
  examples/terraform-module/yarn.lock
  yarn.lock
Labels: auto-approve, dependencies, automerge
