Repository cdktf/projen-cdktf-hybrid-construct, pull requests merged in 2025-04, with the labels that each got.

#203 chore(ci): automate jsii & typescript updates
  .github/MAINTENANCE.md
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/upgrade-jsii-typescript.ts
  scripts/check-jsii-versions.js
  yarn.lock
Labels: auto-approve, automerge

#204 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-main.yml
  .github/workflows/upgrade-projen.yml
  .projenrc.ts
  projenrc/upgrade-cdktf.ts
  projenrc/upgrade-projen.ts
Labels: auto-approve, automerge

#205 chore(deps): upgrade dependencies
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  package.json
  yarn.lock
Labels: auto-approve, dependencies, automerge

#206 chore(deps): upgrade dependencies
  examples/hybrid-module/yarn.lock
  examples/terraform-module/yarn.lock
  yarn.lock
Labels: auto-approve, dependencies, automerge

#207 chore(ci): add missing setup-terraform step to workflow
  .github/workflows/upgrade-jsii-typescript.yml
  projenrc/upgrade-jsii-typescript.ts
Labels: auto-approve, automerge

#208 chore(deps): upgrade jsii & typescript to v5.6
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  examples/hybrid-module/.projen/deps.json
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/.projen/deps.json
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  package.json
  src/hybrid-module.ts
  src/terraform-module.ts
  test/__snapshots__/hybrid-module.test.ts.snap
  test/__snapshots__/terraform-module.test.ts.snap
  yarn.lock
Labels: auto-approve, automerge, automated

#209 chore(deps): upgrade dependencies
  examples/hybrid-module/yarn.lock
  examples/terraform-module/src/.gen/constraints.json
  examples/terraform-module/yarn.lock
  yarn.lock
Labels: auto-approve, dependencies, automerge

#213 chore(deps): upgrade dependencies
  examples/hybrid-module/package.json
  examples/hybrid-module/yarn.lock
  examples/terraform-module/package.json
  examples/terraform-module/yarn.lock
  yarn.lock
Labels: auto-approve, dependencies, automerge
